cat('Running all stages\n\n')
source(file.path('stages', '0_data.R'),local=TRUE)
source(file.path('stages', '1_wrngl.R'), local=TRUE)
source(file.path('stages', '2_chng.R'), local=TRUE)
source(file.path('stages', '3_node_obj.R'),local=TRUE)
source(file.path('stages', '4_cntrst_n.R'), local=TRUE)
source(file.path('stages', '5_phylotime.R'), local=TRUE)
source(file.path('stages', '6_timetree.R'), local=TRUE)
source(file.path('stages', '7_cntrst_chng.R'), local=TRUE)
source(file.path('stages', '8_epi.R'), local=TRUE)
source(file.path('stages', '9_iucn_dwnld.R'), local=TRUE)
source(file.path('stages', '10_iucn_prmttn.R'), local=TRUE)
source(file.path('stages', '12_phyloprmttn.R'), local=TRUE)
cat('\n\nrun.R complete.\n')