cat('Running all stages\n\n')
source(file.path('stages', '0_data.R'),local=TRUE)
source(file.path('stages', '1_wrngl.R'), local=TRUE)
source(file.path('stages', '2_chng.R'), local=TRUE)
source(file.path('stages', '3_node_obj.R'),local=TRUE)
source(file.path('stages', '4_cntrst_n.R'), local=TRUE)
source(file.path('stages', '5_split.R'), local=TRUE)
source(file.path('stages', '6_phylotime.R'), local=TRUE)
source(file.path('stages', '7_timetree.R'), local=TRUE)
source(file.path('stages', '8_cntrst_chng.R'), local=TRUE)
source(file.path('stages', '9_epi.R'), local=TRUE)
cat('\n\nrun.R complete.\n')