cat('Running all stages\n\n')
source(file.path('stages', '0_data.R'),local=TRUE)
source(file.path('stages', '1_chng.R'), local=TRUE)
source(file.path('stages', '2_node_obj.R'),local=TRUE)
source(file.path('stages', '3_cntrst_n.R'), local=TRUE)
source(file.path('stages', '4_phylotime.R'), local=TRUE)
source(file.path('stages', '5_timetree.R'), local=TRUE)
source(file.path('stages', '6_epi.R'), local=TRUE)
source(file.path('stages', '7_analysis.R'), local=TRUE)
source(file.path('stages', '8_plotly.R'), local=TRUE)
cat('\n\nrun.R complete.')